### ISSUE TITLE
Rewrite

### ISSUE THREAD

**Issue by cherche** [Loquacious/arsh-sim#6]
I suggest that we get rid of the current project and start again from scratch so as to avoid mistakes created early on. It also gives us _full customizability_ since it's not built off of someone else's. You (Daman) should probably continue writing the story without coding. It's not entirely necessary but we could also rewrite the story (it's pretty dull and not very well though-out*).

*That means you, Daman

**Comment by Bergenfrundt** [comment]
*we're simulating arshneet of course it's dull and boring

**Comment by cherche** [comment]
Closed since #8 reflects many of the aspects.
