### ISSUE TITLE
INFINITE LOOP

### ISSUE THREAD

**Issue by eravas** [Loquacious/arsh-sim#7]
I'm sure you didn't mean to but if you play video games instead of going to sleep at night, it goes into an infinite loop where you pretend to sleep to avoid being caught playing video games.

**Comment by cherche** [comment]
Not an infinite loop, fully intentional.

**Comment by Bergenfrundt** [comment]
jesus christ harsh you think we wouldn't have noticed that by now

**Comment by eravas** [comment]
Okay, sorry but you don't have to get mad at me; I can't play because I disabled my popups.

**Comment by cherche** [comment]
You didn't have to disable popups.

**Comment by Bergenfrundt** [comment]
why the fuck did you disable popups for a game completely based around popups
